import Head from 'next/head'
import { Container, Row, Col } from "react-bootstrap"

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    <Head>
      <title>My Web | Home</title>
      <meta name='keywords' content='mywebsite'/>
    </Head>
    <Container>
      <Row className='mt-3'>
        <Col xs={12} sm={12} md={12} lg={12} xl={12}>
          <h1>Menus</h1>
          <hr/>
          <h5>Veg</h5>
            <hr/>
            <Row>
              <Col xs={6} sm={6} md={6} lg={6} xl={6}>
                Roti
              </Col>
              <Col xs={6} sm={6} md={6} lg={6} xl={6} style={{textAlign:'right'}}>
                12/-
                </Col>
            </Row>
            <Row>
              <Col xs={6} sm={6} md={6} lg={6} xl={6}>
                Rice
              </Col>
              <Col xs={6} sm={6} md={6} lg={6} xl={6} style={{textAlign:'right'}}>
                50/-
                </Col>
            </Row>
            <hr/>
          <h5>Non-Veg</h5>
            <hr/>
            <Row>
              <Col xs={6} sm={6} md={6} lg={6} xl={6}>
                Roti
              </Col>
              <Col xs={6} sm={6} md={6} lg={6} xl={6} style={{textAlign:'right'}}>
                12/-
                </Col>
            </Row>
            <Row>
              <Col xs={6} sm={6} md={6} lg={6} xl={6}>
                Rice
              </Col>
              <Col xs={6} sm={6} md={6} lg={6} xl={6} style={{textAlign:'right'}}>
                50/-
                </Col>
            </Row>
        </Col>
      </Row> 
    </Container>
    </>
  )
}
  





// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
